#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

expected_documents=(
  "02_REQUIREMENTS/MASTER_COMPLIANCE_MATRIX.md"
  "02_REQUIREMENTS/RFP_REQUIREMENTS_ADMIN_LEGAL_COMMERCIAL.md"
  "02_REQUIREMENTS/RFP_REQUIREMENTS_TECH_AZURE_SECURITY_QA.md"
  "02_REQUIREMENTS/RFP_REQUIREMENTS_FUNCTIONAL_MODULES.md"
  "02_REQUIREMENTS/PROJECT_BACKLOG_RFP_5801_DRC3P.md"
  "02_REQUIREMENTS/RISK_GAP_AMBIGUITY_REGISTER.md"
  "02_REQUIREMENTS/PADF_QUESTIONS_ANEXO_4_DRAFT.md"
  "03_PROPOSAL/PROPOSAL_DOCUMENT_MAP.md"
  "04_AZURE/AZURE_REQUIREMENTS_AND_DECISIONS.md"
  "07_COSTS/COST_REQUIREMENTS_MAP.md"
  "09_TEAM/TEAM_REQUIREMENTS_GAP_ANALYSIS.md"
  "docs/EVALUATION_WIN_STRATEGY.md"
  "docs/EXECUTIVE_RFP_REPORT.md"
  "docs/NEXT_PHASE_READINESS.md"
  "99_EVIDENCE/RFP_EXTRACTION_EVIDENCE.md"
  "11_DELIVERY/QA-CHECKLIST-FINAL.md"
  "SOLUTION_BLUEPRINT/README.md"
  "SOLUTION_BLUEPRINT/01_EXECUTIVE_VISION.md"
  "SOLUTION_BLUEPRINT/02_SOLUTION_ARCHITECTURE.md"
  "SOLUTION_BLUEPRINT/03_BUSINESS_PROCESS.md"
  "SOLUTION_BLUEPRINT/04_TECHNICAL_ARCHITECTURE.md"
  "SOLUTION_BLUEPRINT/05_AZURE_HIGH_LEVEL.md"
  "SOLUTION_BLUEPRINT/06_SECURITY_MODEL.md"
  "SOLUTION_BLUEPRINT/07_DEVSECOPS.md"
  "SOLUTION_BLUEPRINT/08_DATA_ARCHITECTURE.md"
  "SOLUTION_BLUEPRINT/09_INTEGRATION_MODEL.md"
  "SOLUTION_BLUEPRINT/10_DEPLOYMENT_MODEL.md"
  "SOLUTION_BLUEPRINT/11_OPERATION_MODEL.md"
  "SOLUTION_BLUEPRINT/12_SUPPORT_MODEL.md"
  "SOLUTION_BLUEPRINT/13_TESTING_STRATEGY.md"
  "SOLUTION_BLUEPRINT/14_MIGRATION_STRATEGY.md"
  "SOLUTION_BLUEPRINT/15_CHANGE_MANAGEMENT.md"
  "SOLUTION_BLUEPRINT/16_TRAINING_PLAN.md"
  "SOLUTION_BLUEPRINT/17_DISASTER_RECOVERY.md"
  "SOLUTION_BLUEPRINT/18_MONITORING_OBSERVABILITY.md"
  "SOLUTION_BLUEPRINT/19_INNOVATION_PROPOSALS.md"
  "SOLUTION_BLUEPRINT/20_EXECUTIVE_DIFFERENTIATORS.md"
  "SOLUTION_BLUEPRINT/21_WOW_FACTORS.md"
  "SOLUTION_BLUEPRINT/WHY_JUSTECH_SHOULD_WIN.md"
  "UX_MASTER/README.md"
  "UX_MASTER/01_DESIGN_PHILOSOPHY.md"
  "UX_MASTER/02_DESIGN_SYSTEM.md"
  "UX_MASTER/03_COLOR_SYSTEM.md"
  "UX_MASTER/04_TYPOGRAPHY.md"
  "UX_MASTER/05_ICONOGRAPHY.md"
  "UX_MASTER/06_LAYOUT_SYSTEM.md"
  "UX_MASTER/07_NAVIGATION.md"
  "UX_MASTER/08_COMPONENT_LIBRARY.md"
  "UX_MASTER/09_DASHBOARD_DESIGN.md"
  "UX_MASTER/10_MODULES_UX.md"
  "UX_MASTER/11_MOBILE_STRATEGY.md"
  "UX_MASTER/12_ACCESSIBILITY.md"
  "UX_MASTER/13_USER_JOURNEYS.md"
  "UX_MASTER/14_PERSONAS.md"
  "UX_MASTER/15_UI_STANDARDS.md"
  "UX_MASTER/16_REPORTS_DESIGN.md"
  "UX_MASTER/17_PRINT_DESIGN.md"
  "UX_MASTER/18_NOTIFICATION_SYSTEM.md"
  "UX_MASTER/19_EMPTY_STATES.md"
  "UX_MASTER/20_ERROR_HANDLING.md"
  "UX_MASTER/21_LOADING_STATES.md"
  "UX_MASTER/22_DATA_VISUALIZATION.md"
  "UX_MASTER/23_EXECUTIVE_DASHBOARD.md"
  "UX_MASTER/24_DESIGN_DECISIONS.md"
)

future_documents=(
  "01_RFP/RFP-ORIGINAL.md"
  "03_PROPOSAL/TEC-OFERTA-TECNICA.md"
  "07_COSTS/ECO-OFERTA-ECONOMICA.md"
  "09_TEAM/EQP-MATRIZ-RACI.md"
  "10_LEGAL/LEG-CHECKLIST.md"
)

echo "Checking expected bid documents..."

missing_count=0
for document in "${expected_documents[@]}"; do
  if [[ -e "${PROJECT_ROOT}/${document}" ]]; then
    echo "OK ${document}"
  else
    echo "PENDING ${document}"
    missing_count=$((missing_count + 1))
  fi
done

echo "Pending documents: ${missing_count}"

echo "Checking future phase documents..."
future_count=0
for document in "${future_documents[@]}"; do
  if [[ -e "${PROJECT_ROOT}/${document}" ]]; then
    echo "OK ${document}"
  else
    echo "FUTURE ${document}"
    future_count=$((future_count + 1))
  fi
done

echo "Future phase documents not created by design: ${future_count}"
